# Generated by Django 5.0.3 on 2024-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_friendslist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendslist',
            old_name='is_connected',
            new_name='is_accept',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
