# Generated by Django 5.0.3 on 2024-03-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_is_connected_friendslist_is_accept_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendslist',
            unique_together=set(),
        ),
    ]
