# Generated by Django 5.0.3 on 2024-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authendications', '0005_user_blocked_list_user_friends_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
